apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: testm-deployment
spec:
  selector:
    matchLabels:
      app: testm
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: testm
    spec:
      containers:
      - name: testm
        image: vugu/testm:latest
        ports:
        - containerPort: 8812
